steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'api/Dockerfile', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/natillera-repo/natillera-beta:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/natillera-repo/natillera-beta:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'natillera-beta'
      - '--image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/natillera-repo/natillera-beta:$COMMIT_SHA'
      - '--region=southamerica-east1'
      - '--platform=managed'
images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/natillera-repo/natillera-beta:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
